### ISSUE TITLE
Not stripping logs

### ISSUE THREAD

**Issue by ermaker** [mattheworiordan/fluent-plugin-color-stripper#1]
Hello,

I'm using [nginx-proxy](https://github.com/jwilder/nginx-proxy) and it uses [forego](https://github.com/ddollar/forego) internally.

And here is the log (json format):

```
{"log":"\u001b[0;36;1mnginx.1    | \u001b[0mlocalhost 10.0.2.2 - - ..."}
{"log":"\u001b[0m\u001b[0;33;1mdockergen.1 | \u001b[0;31;1m2015/11/22 04:34:28 Received event start for container ..."}
```

The first one is stripped color well, but not the second one.

Do you know about this issue?

**Comment by mattheworiordan** [comment]
Sorry, no, why don't you write a test that injects this data, and I can then try and fix the test?  If you do a PR with a test, I will make some time to look at it

**Comment by mattheworiordan** [comment]
Oops, I didn't see https://github.com/mattheworiordan/fluent-plugin-color-stripper/pull/2.

Thanks @ermaker!

**Comment by ermaker** [comment]
Thanks!
